spring:
  datasource:
    url: jdbc:mysql://localhost/consolestore?serverTimezone=UTC
    password: root
    username: root

  jpa:
    show-sql: false
    generate-ddl: true
  main:
    web-application-type: none